# -*- coding: utf-8 -*-
"""pad16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HLcK8YunYWMGF7C2u1tuyn-fZMS0Kw9G

# Bibliotecas
"""

# Instalar bibliotecas
# !pip install python-bcb
# !pip install ipeadatapy
# !pip install sidrapy

# Importar bibliotecas
from bcb import sgs
import pandas as pd
import ipeadatapy as ipea
import sidrapy as sidra

"""# Coleta de dados do BCB"""

# Importar 1 série do SGS/BCB
dados_sgs = sgs.get(codes = 22099, start = "2010-01-01")
dados_sgs

# Importar múltiplas séries do SGS/BCB
dados_sgs = sgs.get(codes = {"pib": 22099, "ipca": 433})
dados_sgs.tail(10)

# Importar dados do IPCA (expectativa anual) com o pandas
dados_expectativas = pd.read_csv(
    filepath_or_buffer = "https://olinda.bcb.gov.br/olinda/servico/Expectativa" +
    "s/versao/v1/odata/ExpectativasMercadoAnuais?$filter=Indicador%20eq%20'IPC" +
    "A'%20and%20Data%20ge%20'2021-01-01'&$format=text/csv",
    decimal = ","
    )
dados_expectativas

"""# Coleta de dados do IPEADATA"""

# Obter código das séries do IPEADATA
codigos_ipeadata = ipea.list_series()
codigos_ipeadata

# Buscar série de interesse
codigos_ipeadata[codigos_ipeadata.CODE.str.contains("CAGED")]

# Importar dados do CAGED pelo IPEDATA
dados_ipeadata = ipea.timeseries(series = "CAGED12_SALDON12")
dados_ipeadata

"""# Coleta de dados do Sidra

**Aviso**: o código abaixo foi atualizado para facilitar a reprodução, usando uma biblioteca que se conecta a API.

Para mais informações veja esse tutorial: https://analisemacro.com.br/economia/indicadores/coletando-dados-do-sidra-com-o-python/
"""

# Importar tabela 7060 do Sidra/IBGE
dados_sidra = sidra.get_table(
    table_code = "7060",
    territorial_level = "1",
    ibge_territorial_code = "all",
    variable = "63,66,2265",
    period = "all",
    classifications = {"315": "7169,7170,7445,7486,7558,7625,7660,7712,7766,7786"}
    )
dados_sidra